#include <Arduino.h>
#include <WebSocketsServer.h>
#include <ESP8266WebServer.h>
#include <ESP8266WebServerSecure.h>
#include <ESP8266mDNS.h>
#include <Hash.h>
#include <ESP8266WiFi.h>
#include <WiFiManager.h>
#include <DoubleResetDetect.h>
#include <Ticker.h>
